---
  # Here are bugfixes or workarrounds
- name: Create /etc/openshift to fix bug 1419654
  file:
    path: /etc/openshift
    state: directory
    mode: 0755
  when: "'os' in inventory_hostname"

# - name: Install RHEL docker distro
#   yum:
#     name: "docker-distribution"
#     state: present
#
# - name: Start RHEL docker distro
#   systemd:
#     name: "docker-distribution"
#     state: started
#     enabled: yes
